import img1 from '../assets/images/profile_img.png';
import edit1 from '../assets/images/edit_ion.png';
import delete1 from '../assets/images/delete_ion.png';

const SubCatefiriesAdd={
    "idNumber":"No",
    "subTitle":"Sub Category",
    "maincategory":"Main Category",
    "bannertitle":"Banner",
    "action":"Action",
     "content":[
    {
        "id":1,
        "image":img1,
        "sub":"Web Development",
        "main":'Technology',
        "bannerbtn":'View',
        "edit_img":edit1,
        "delete_img":delete1,
    },
    {
        "id":2,
        "image":img1,
        "sub":"Web Development",
        "main":'Technology',
        "bannerbtn":'View',
        "edit_img":edit1,
        "delete_img":delete1,
    },
    {
        "id":3,
        "image":img1,
        "sub":"Web Development",
        "main":'Technology',
        "bannerbtn":'View',
        "edit_img":edit1,
        "delete_img":delete1,
    },
    {
        "id":4,
        "image":img1,
        "sub":"Web Development",
        "main":'Technology',
        "bannerbtn":'View',
        "edit_img":edit1,
        "delete_img":delete1,
    },
    {
        "id":5,
        "image":img1,
        "sub":"Web Development",
        "main":'Technology',
        "bannerbtn":'View',
        "edit_img":edit1,
        "delete_img":delete1,
    },
    {
        "id":6,
        "image":img1,
        "sub":"Web Development",
        "main":'Technology',
        "bannerbtn":'View',
        "edit_img":edit1,
        "delete_img":delete1,
    },
    {
        "id":7,
        "image":img1,
        "sub":"Web Development",
        "main":'Technology',
        "bannerbtn":'View',
        "edit_img":edit1,
        "delete_img":delete1,
    },
    {
        "id":8,
        "image":img1,
        "sub":"Web Development",
        "main":'Technology',
        "bannerbtn":'View',
        "edit_img":edit1,
        "delete_img":delete1,
    },
    {
        "id":9,
        "image":img1,
        "sub":"Web Development",
        "main":'Technology',
        "bannerbtn":'View',
        "edit_img":edit1,
        "delete_img":delete1,
    },
    {
        "id":10,
        "image":img1,
        "sub":"Web Development",
        "main":'Technology',
        "bannerbtn":'View',
        "edit_img":edit1,
        "delete_img":delete1,
    },
]
}
export default SubCatefiriesAdd